"""总览模块路由。"""

from django.urls import path

from . import inline_tasks, telemetry_views, topology_views, views


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("guides/nodes/", views.node_deployment_guide, name="node-deployment-guide"),
    path("guides/nodes/scripts/download/", views.sshd_script_archive_download, name="sshd-script-archive-download"),
    path(
        "guides/nodes/scripts/linux/server-kit-node-linux.sh",
        views.linux_node_script_download,
        name="linux-node-script-download",
    ),
    path(
        "guides/nodes/scripts/linux/download/",
        views.linux_node_script_download,
        name="linux-node-script-download-legacy",
    ),
    path("guides/nodes/sshd/<str:platform>/download/", views.sshd_script_download, name="sshd-script-download"),
    path("audit/", views.task_audit, name="task-audit"),
    path("tasks/<str:task_id>/", views.change_task_detail, name="change-task-detail"),
    path("tasks/<str:task_id>/cancel/", views.change_task_cancel, name="change-task-cancel"),
    path("inline-tasks/execute/", inline_tasks.execute, name="inline-task-execute"),
    path("inline-tasks/<str:task_id>/", inline_tasks.status, name="inline-task-status"),
    path("accounts/", views.accounts, name="accounts"),
    path("deploy/", views.deployment_wizard, name="deployment-wizard"),
    path("healthz", views.health, name="health"),
    path("security/transactions/", views.security_transactions, name="security-transactions"),
    path("security/transactions/<str:transaction_type>/preview/", views.security_transaction_preview, name="security-transaction-preview"),
    path("security/transactions/<str:transaction_type>/execute/", views.security_transaction_execute, name="security-transaction-execute"),
    path("backups/", views.backups, name="backups"),
    path("backups/<str:backup_id>/download/", views.backup_download, name="backup-download"),
    path("backups/<str:backup_id>/delete/preview/", views.backup_delete_preview, name="backup-delete-preview"),
    path("backups/<str:backup_id>/delete/execute/", views.backup_delete_execute, name="backup-delete-execute"),
    path("files/", views.file_resource_list, name="file-resources"),
    path("files/add/", views.file_resource_add, name="file-resource-add"),
    path("files/<str:resource_id>/delete/preview/", views.file_resource_delete_preview, name="file-resource-delete-preview"),
    path("files/<str:resource_id>/delete/execute/", views.file_resource_delete_execute, name="file-resource-delete-execute"),
    path("files/<str:resource_id>/<str:resource>/", views.file_resource_secret, name="file-resource-secret"),
    path("network/nodes/", views.network_nodes, name="network-nodes"),
    path("network/topology/", topology_views.node_connections, name="network-topology"),
    path("network/telemetry/", telemetry_views.node_telemetry, name="network-telemetry"),
    path("network/notices/dismiss/", views.network_notice_dismiss, name="network-notice-dismiss"),
    path("sensitive/unlock/", views.sensitive_unlock, name="sensitive-unlock"),
    path("network/nodes/preview/", views.network_node_preview, name="network-node-preview"),
    path("network/nodes/execute/", views.network_node_execute, name="network-node-execute"),
    path("network/nodes/exits/preview/", views.network_node_exits_preview, name="network-node-exits-preview"),
    path("network/nodes/exits/execute/", views.network_node_exits_execute, name="network-node-exits-execute"),
    path("network/nodes/domains/preview/", views.network_node_domains_preview, name="network-node-domains-preview"),
    path("network/addresses/domains/preview/", views.network_address_domains_preview, name="network-address-domains-preview"),
    path("network/nodes/domains/execute/", views.network_node_domains_execute, name="network-node-domains-execute"),
    path("network/public-endpoint/preview/", views.network_public_endpoint_preview, name="network-public-endpoint-preview"),
    path("network/public-endpoint/execute/", views.network_public_endpoint_execute, name="network-public-endpoint-execute"),
    path("network/duckdns/preview/", views.network_duckdns_preview, name="network-duckdns-preview"),
    path("network/duckdns/execute/", views.network_duckdns_execute, name="network-duckdns-execute"),
    path("network/permissions/preview/", views.network_permission_preview, name="network-permission-preview"),
    path("network/permissions/execute/", views.network_permission_execute, name="network-permission-execute"),
    path("network/permissions/batch/preview/", views.network_permission_batch_preview, name="network-permission-batch-preview"),
    path("network/permissions/batch/execute/", views.network_permission_batch_execute, name="network-permission-batch-execute"),
    path("network/permissions/batch/<str:task_id>/", views.network_permission_batch_status, name="network-permission-batch-status"),
    path("network/subscriptions/", views.network_subscriptions, name="network-subscriptions"),
    path("network/proxy/", views.network_proxy_resources, name="network-proxy-resources"),
    path("network/proxy/execute/", views.network_proxy_resource_execute, name="network-proxy-resource-execute"),
    path("network/proxy/<str:item_id>/<str:resource>/", views.network_proxy_secret, name="network-proxy-secret"),
    path("network/subscriptions/preview/", views.network_subscription_preview, name="network-subscription-preview"),
    path("network/subscriptions/execute/", views.network_subscription_execute, name="network-subscription-execute"),
    path("network/subscriptions/<str:item_id>/rotate/preview/", views.network_subscription_rotate_preview, name="network-subscription-rotate-preview"),
    path("network/subscriptions/<str:item_id>/rotate/execute/", views.network_subscription_rotate_execute, name="network-subscription-rotate-execute"),
    path("network/subscriptions/<str:item_id>/state/preview/", views.network_subscription_state_preview, name="network-subscription-state-preview"),
    path("network/subscriptions/<str:item_id>/state/execute/", views.network_subscription_state_execute, name="network-subscription-state-execute"),
    path("services/<str:service_id>/", views.service_detail, name="service-detail"),
    path("services/firewall/ports/preview/", views.firewall_port_preview, name="firewall-port-preview"),
    path("services/firewall/ports/execute/", views.firewall_port_execute, name="firewall-port-execute"),
    path("services/managed-ports/preview/", views.managed_port_preview, name="managed-port-preview"),
    path("services/managed-ports/execute/", views.managed_port_execute, name="managed-port-execute"),
    path("services/ssh/keys/preview/", views.ssh_key_preview, name="ssh-key-preview"),
    path("services/ssh/keys/execute/", views.ssh_key_execute, name="ssh-key-execute"),
    path("services/clash/subscriptions/<str:item_id>/copy/", views.clash_subscription_copy, name="clash-subscription-copy"),
    path("services/clash/subscriptions/<str:item_id>/qr/", views.clash_subscription_qr, name="clash-subscription-qr"),
    path(
        "services/<str:service_id>/actions/preview/",
        views.service_action_preview,
        name="service-action-preview",
    ),
    path(
        "services/<str:service_id>/actions/execute/",
        views.service_action_execute,
        name="service-action-execute",
    ),
]
